DELETE FROM products;

INSERT INTO products (name, description, price, category, image_url, stock, rating) VALUES
  ('BB Cream', 'Allotment pending details', 899, 'Makeup', '/products/bb-cream.jpeg', 100, 5),
  ('Stroke Cream', 'Allotment pending details', 999, 'Makeup', '/products/stroke-cream.jpeg', 100, 5),
  ('Primer', 'Allotment pending details', 1099, 'Makeup', '/products/primer.jpeg', 100, 5),
  ('Foundation', 'Allotment pending details', 1299, 'Makeup', '/products/foundation.jpeg', 100, 5),
  ('Compact Powder', 'Allotment pending details', 799, 'Makeup', '/products/compact-powder.jpeg', 100, 5),
  ('Eyeliner', 'Allotment pending details', 499, 'Makeup', '/products/eyeliner.jpeg', 100, 5),
  ('Mascara', 'Allotment pending details', 549, 'Makeup', '/products/mascara.jpeg', 100, 5),
  ('Kajal', 'Allotment pending details', 299, 'Makeup', '/products/kajal.jpeg', 100, 5),
  ('Sindoor', 'Allotment pending details', 199, 'Makeup', '/products/sindoor.jpeg', 100, 5),
  ('Eyebrow Pencil', 'Allotment pending details', 349, 'Makeup', '/products/eyebrow-pencil.jpeg', 100, 5),
  ('Mini Makeup Brush Kit', 'Allotment pending details', 1499, 'Makeup', '/products/mini-makeup-brush-kit.jpeg', 100, 5),
  ('Keysoul Wipes', 'Allotment pending details', 149, 'Makeup', '/products/wipes.jpeg', 100, 5),
  ('Lip Kit', 'Lip Liner, Lipstick, Lip Balm, Lip Gloss, Lip Oil', 1999, 'Makeup', '/products/lip-kit.jpeg', 100, 5),
  ('Eyeshadow Palette', 'Allotment pending details', 1899, 'Makeup', '/products/eyeshadow-palette.jpeg', 100, 5),
  ('3-in-1 Shine Palette', 'Blush, Highlighter, Contour', 2199, 'Makeup', '/products/3-in-1-shine-palette.jpeg', 100, 5),
  ('3-in-1 Tint', 'Eyes, Lip, Blush', 899, 'Makeup', '/products/3-in-1-tint.jpeg', 100, 5),
  ('Concealer', 'High coverage creamy concealer', 599, 'Makeup', '/products/concealer.jpeg', 100, 5),
  ('Lip Balm', 'Nourishing lip protection', 249, 'Makeup', '/products/lip-balm.jpeg', 100, 5),
  ('Lip Balm V2', 'Advanced lip hydration', 299, 'Makeup', '/products/lip-balm-2.jpeg', 100, 5),
  ('Face Wash', 'Allotment pending details', 449, 'Skincare', '/products/face-wash.jpeg', 100, 5),
  ('Toner', 'Allotment pending details', 499, 'Skincare', '/products/toner.jpeg', 100, 5),
  ('Sunscreen', 'Allotment pending details', 699, 'Skincare', '/products/sunscreen.jpeg', 100, 5),
  ('Moisturizer (Oily Skin)', 'Allotment pending details', 549, 'Skincare', '/products/moisturizer-oily.jpeg', 100, 5),
  ('Moisturizer (Normal/Combination)', 'Allotment pending details', 549, 'Skincare', '/products/moisturizer-normal.jpeg', 100, 5),
  ('Moisturizer (Dry Skin)', 'Allotment pending details', 549, 'Skincare', '/products/moisturizer-dry.jpeg', 100, 5),
  ('Day Serum', 'Allotment pending details', 899, 'Skincare', '/products/day-serum.jpeg', 100, 5),
  ('Night Serum', 'Allotment pending details', 949, 'Skincare', '/products/night-serum.jpeg', 100, 5),
  ('Hair Serum', 'Allotment pending details', 799, 'Skincare', '/products/hair-serum.jpeg', 100, 5),
  ('Serum Kit', 'Day + Night + Hair', 2499, 'Skincare', '/products/serum-kit.jpeg', 100, 5),
  ('Hair Revival Kit', 'Allotment pending details', 2999, 'Hair Care', '/products/hair-revival-kit.jpeg', 100, 5),
  ('Anti-dandruff Shampoo', 'Allotment pending details', 649, 'Hair Care', '/products/anti-dandruff-shampoo.jpeg', 100, 5),
  ('Hair Fall Control Shampoo', 'Allotment pending details', 699, 'Hair Care', '/products/hair-fall-control-shampoo.jpeg', 100, 5),
  ('Herbal Shampoo', 'Allotment pending details', 549, 'Hair Care', '/products/herbal-shampoo.jpeg', 100, 5),
  ('Herbal Oil', 'Allotment pending details', 449, 'Hair Care', '/products/herbal-oil.jpeg', 100, 5),
  ('Moringa Shampoo', 'Allotment pending details', 799, 'Hair Care', '/products/hair-fall-control-shampoo.jpeg', 100, 5),
  ('Moringa Oil', 'Allotment pending details', 699, 'Hair Care', '/products/moringa-oil.jpeg', 100, 5),
  ('Moringa Conditioner', 'Allotment pending details', 799, 'Hair Care', '/products/hair-conditioner.jpeg', 100, 5),
  ('Moringa Mini Facial Kit', 'Allotment pending details', 1499, 'Others', '/products/moringa-mini-facial-kit.jpeg', 100, 5),
  ('Foot Cream', 'Allotment pending details', 399, 'Others', '/products/foot-cream.jpeg', 100, 5),
  ('Moringa Scrub', 'Allotment pending details', 599, 'Others', '/products/moringa-scrub.jpeg', 100, 5),
  ('Moringa Soap', 'Allotment pending details', 149, 'Others', '/products/moringa-soap.jpeg', 100, 5),
  ('Nysa Sensation Soap', 'Allotment pending details', 199, 'Others', '/products/nysa-soap.jpeg', 100, 5),
  ('Perfume', 'Allotment pending details', 1999, 'Others', '/products/perfume.jpeg', 100, 5);
